name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  CI: true

jobs:
  lint_js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/pnpm
      - name: ESLint
        run: pnpm run lint:js

  typecheck:
    name: Type Checking
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/pnpm
      - run: pnpm build:theme-data
      - run: pnpm tsc --noEmit
        working-directory: tests

  tests:
    name: Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/pnpm
      - run: pnpm test

  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: [tests]

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm
      - run: pnpm build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@e87c8ed249971350e47fab7515075f44eb134e5b # v1.7.0
        with:
          publish: pnpm release
          title: "Release Preview"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
